import pytest
import asyncio
import json
from unittest.mock import MagicMock, AsyncMock, patch
from ghost_agent.core.agent import GhostAgent, GhostContext

@pytest.fixture
def agent():
    context = MagicMock(spec=GhostContext)
    context.llm_client = MagicMock()
    context.llm_client.vision_clients = None
    context.sandbox_dir = "/tmp/sandbox"
    context.args = MagicMock()
    context.args.shell = "bash"
    context.args.max_context = 8000
    context.args.temperature = 0.5
    context.args.smart_memory = 0.0
    context.args.use_planning = False
    context.args.model = "qwen2.5"

    context.profile_memory = MagicMock()
    context.profile_memory.get_context_string.return_value = ""
    context.memory_system = None
    context.skill_memory = None
    context.scratchpad = MagicMock()
    context.scratchpad.list_all.return_value = ""
    return GhostAgent(context)

@pytest.mark.asyncio
async def test_xml_precedence_over_embedded_json(agent):
    """
    Test that explicit <function name="..."> tags take precedence over standalone dictionaries
    in the payload. This prevents dictionary literals inside code (e.g., Python code)
    from confusing the parser into thinking it's a JSON JSON argument block.
    """
    message = """Here is the Python script:
<tool_call>
<function name="run_python">
<parameter name="code">
def get_data():
    return {"status": "ok", "value": 42} # This dict should NOT be parsed as the tool argument
</parameter>
</function>
</tool_call>
"""
    agent.context.llm_client.chat_completion = AsyncMock(side_effect=[
        {"choices": [{"message": {"content": message}}]},
        {"choices": [{"message": {"content": "I am done."}}]}
    ])

    background_tasks = MagicMock()
    body = {"messages": [{"role": "user", "content": "please run the tool"}]}

    with patch("ghost_agent.core.agent.get_active_tool_definitions", return_value=[{"function": {"name": "run_python"}}]):
        await agent.handle_chat(body, background_tasks)
        
    tool_calls = body['messages'][2].get('tool_calls', [])
    assert len(tool_calls) == 1
    
    # It should correctly identify "run_python" matching the <function name="..."> tag
    assert tool_calls[0]["function"]["name"] == "run_python"
    
    args = json.loads(tool_calls[0]["function"]["arguments"])
    expected_code = '''def get_data():
    return {"status": "ok", "value": 42} # This dict should NOT be parsed as the tool argument'''
    
    assert args["code"] == expected_code


@pytest.mark.asyncio
async def test_xml_fallback_qwen_multiline(agent):
    """Test that XML parsing correctly extracts multiline parameters."""
    message = """I will run the code.
<tool_call>
<function name="run_python">
<parameter name="code">
def hello_world():
    print("Hello, world!")
    
hello_world()
</parameter>
</function>
</tool_call>
"""
    agent.context.llm_client.chat_completion = AsyncMock(side_effect=[
        {"choices": [{"message": {"content": message}}]},
        {"choices": [{"message": {"content": "I am done."}}]}
    ])

    background_tasks = MagicMock()
    body = {"messages": [{"role": "user", "content": "please run the tool"}]}

    with patch("ghost_agent.core.agent.get_active_tool_definitions", return_value=[{"function": {"name": "run_python"}}]):
        await agent.handle_chat(body, background_tasks)
        
    tool_calls = body['messages'][2].get('tool_calls', [])
    assert len(tool_calls) == 1
    assert tool_calls[0]["function"]["name"] == "run_python"
    
    args = json.loads(tool_calls[0]["function"]["arguments"])
    expected_code = '''
def hello_world():
    print("Hello, world!")
    
hello_world()
'''
    assert args["code"] == expected_code.strip()


@pytest.mark.asyncio
async def test_xml_fallback_qwen_pure_xml_format(agent):
    """Test that pure XML parsing (as generated by the new prompt) extracts correctly."""
    message = """Here is the new format:
<tool_call>
<function name="run_python">
<parameter name="code">
def new_format():
    print("Works perfectly")
</parameter>
</function>
</tool_call>
"""
    agent.context.llm_client.chat_completion = AsyncMock(side_effect=[
        {"choices": [{"message": {"content": message}}]},
        {"choices": [{"message": {"content": "I am done."}}]}
    ])

    background_tasks = MagicMock()
    body = {"messages": [{"role": "user", "content": "please run the tool"}]}

    with patch("ghost_agent.core.agent.get_active_tool_definitions", return_value=[{"function": {"name": "run_python"}}]):
        await agent.handle_chat(body, background_tasks)
        
    tool_calls = body['messages'][2].get('tool_calls', [])
    assert len(tool_calls) == 1
    assert tool_calls[0]["function"]["name"] == "run_python"
    
    args = json.loads(tool_calls[0]["function"]["arguments"])
    expected_code = '''
def new_format():
    print("Works perfectly")
'''
    assert args["code"] == expected_code.strip()


@pytest.mark.asyncio
async def test_json_fallback_when_xml_is_missing(agent):
    """Test that if no <function name="..."> tags are present, it successfully falls back to JSON inside <tool_call>."""
    message = """Here is the call:
<tool_call>
{"name": "test_json", "arguments": {"foo": "bar"}}
</tool_call>"""

    agent.context.llm_client.chat_completion = AsyncMock(side_effect=[
        {"choices": [{"message": {"content": message}}]},
        {"choices": [{"message": {"content": "I am done."}}]}
    ])
    
    background_tasks = MagicMock()
    body = {"messages": [{"role": "user", "content": "please run the tool"}]}
    
    with patch("ghost_agent.core.agent.get_active_tool_definitions", return_value=[{"function": {"name": "test_json"}}]):
        await agent.handle_chat(body, background_tasks)
        
    tool_calls = body['messages'][2].get('tool_calls', [])
    assert len(tool_calls) == 1
    assert tool_calls[0]["function"]["name"] == "test_json"
    args = json.loads(tool_calls[0]["function"]["arguments"])
    assert args["foo"] == "bar"


@pytest.mark.parametrize("content,want_name,want_args", [
    # Plain `<function = "x">` with space around `=` and no `name` attr.
    # Captured from Qwen3.6-35B-A3B output in the 08:01 self-play trace.
    (
        '<tool_call>\n<function = "file_system">\n<parameter = "operation">read</parameter>\n<parameter = "path">sales.csv</parameter>\n</function>\n</tool_call>',
        "file_system",
        {"operation": "read", "path": "sales.csv"},
    ),
    # `<function_name="x">` hallucination — underscore alias.
    (
        '<tool_call>\n<function_name="execute">\n<parameter name="filename">sort.py</parameter>\n</function>\n</tool_call>',
        "execute",
        {"filename": "sort.py"},
    ),
    # `<function_name = "x">` — underscore alias with padded equals.
    (
        '<tool_call>\n<function_name = "file_system">\n<parameter name = "operation">write</parameter>\n<parameter name = "path">solution.py</parameter>\n<parameter name = "content">print(1)</parameter>\n</function>\n</tool_call>',
        "file_system",
        {"operation": "write", "path": "solution.py", "content": "print(1)"},
    ),
    # Mixed: dropped `name` on function, padded equals on parameters.
    (
        '<tool_call>\n<function = "execute">\n<parameter name = "command">head -5 sales.csv</parameter>\n</function>\n</tool_call>',
        "execute",
        {"command": "head -5 sales.csv"},
    ),
])
@pytest.mark.asyncio
async def test_qwen36_sloppy_xml_attributes_parse(agent, content, want_name, want_args):
    """Regression: Qwen3.6 emits XML with padded `=` and `function_name`
    aliases that the original parser regex `<function(?:\\s+name=|=)` did
    not match, causing every tool call to fall through to
    `system_parse_error`. The pre-parser normalization rewrites these
    variants into canonical `<function name="...">` form so the existing
    regex chain matches.
    """
    agent.context.llm_client.chat_completion = AsyncMock(side_effect=[
        {"choices": [{"message": {"content": content}}]},
        {"choices": [{"message": {"content": "done."}}]},
    ])
    background_tasks = MagicMock()
    body = {"messages": [{"role": "user", "content": "run it"}]}
    with patch(
        "ghost_agent.core.agent.get_active_tool_definitions",
        return_value=[{"function": {"name": want_name}}],
    ):
        await agent.handle_chat(body, background_tasks)
    tool_calls = body["messages"][2].get("tool_calls", [])
    assert len(tool_calls) == 1, f"expected 1 call, got {tool_calls}"
    assert tool_calls[0]["function"]["name"] == want_name
    got_args = json.loads(tool_calls[0]["function"]["arguments"])
    for k, v in want_args.items():
        assert got_args.get(k) == v, f"param {k!r}: want {v!r}, got {got_args.get(k)!r}"


@pytest.mark.asyncio
async def test_vision_analysis_xml_fallback(agent):
    """Test that vision_analysis extracts the target even if the XML is malformed."""
    message = """Here is the broken call:
<tool_call>
<name>vision_analysis</name>
<target>vision_123.jpg</target>
</tool_call>"""

    agent.context.llm_client.chat_completion = AsyncMock(side_effect=[
        {"choices": [{"message": {"content": message}}]},
        {"choices": [{"message": {"content": "I am done."}}]}
    ])
    
    background_tasks = MagicMock()
    body = {"messages": [{"role": "user", "content": "describe this"}]}
    
    with patch("ghost_agent.core.agent.get_active_tool_definitions", return_value=[{"function": {"name": "vision_analysis"}}]):
        await agent.handle_chat(body, background_tasks)
        
    tool_calls = body['messages'][2].get('tool_calls', [])
    assert len(tool_calls) == 1
    assert tool_calls[0]["function"]["name"] == "vision_analysis"
    args = json.loads(tool_calls[0]["function"]["arguments"])
    assert args["target"] == "vision_123.jpg"
    assert args["action"] == "describe_picture"


@pytest.mark.asyncio
async def test_system_parse_error_on_mangled_xml_and_json(agent):
    """Test that if neither <function name="..."> nor valid JSON is found within a <tool_call>, it emits system_parse_error."""
    message = """Here is the broken call:
<tool_call>
<func_tion=broken>
Some random text { missing brace and stuff
</tool_call>"""

    agent.context.llm_client.chat_completion = AsyncMock(side_effect=[
        {"choices": [{"message": {"content": message}}]},
        {"choices": [{"message": {"content": "I fixed it", "tool_calls": []}}]}
    ])
    
    background_tasks = MagicMock()
    body = {"messages": [{"role": "user", "content": "please run the tool"}]}
    
    with patch("ghost_agent.core.agent.get_active_tool_definitions", return_value=[]):
        await agent.handle_chat(body, background_tasks)
        
    # The agent should have injected a system_parse_error feedback
    # Let's inspect the payload sent in the second call
    assert agent.context.llm_client.chat_completion.call_count >= 2
    second_call_args = agent.context.llm_client.chat_completion.call_args_list[1][0][0]
    sent_messages = second_call_args["messages"]
    
    error_tool_msg = next((m for m in sent_messages if "SYSTEM ERROR" in str(m.get("content"))), None)
    assert error_tool_msg is not None, "Agent did not inject system_parse_error feedback for invalid XML/JSON."
    # Recovery hint is now reason-specific. For the mangled `<func_tion>`
    # fixture here (no valid <function> tag), the branch is
    # "no_function_tag" which must still surface the correct shape.
    content = error_tool_msg["content"]
    assert "SYSTEM ERROR" in content
    assert (
        "no `<function" in content
        or "did not parse" in content
        or "CUT OFF" in content
    )


@pytest.mark.asyncio
async def test_file_system_fallback_optional_content(agent):
    """Test that file_system regex fallback accepts read/list operations without content."""
    message = """Let's read the file.
<tool_call>
<function name="file_system">
<parameter name="operation">read</parameter>
<parameter name="path">test.txt</parameter>
</function>
</tool_call>"""
    agent.context.llm_client.chat_completion = AsyncMock(side_effect=[
        {"choices": [{"message": {"content": message}}]},
        {"choices": [{"message": {"content": "I am done."}}]}
    ])
    
    background_tasks = MagicMock()
    body = {"messages": [{"role": "user", "content": "read test.txt"}]}
    
    with patch("ghost_agent.core.agent.get_active_tool_definitions", return_value=[{"function": {"name": "file_system"}}]):
        await agent.handle_chat(body, background_tasks)
        
    tool_calls = body['messages'][2].get('tool_calls', [])
    assert len(tool_calls) == 1
    assert tool_calls[0]["function"]["name"] == "file_system"
    args = json.loads(tool_calls[0]["function"]["arguments"])
    assert args["operation"] == "read"
    assert args["path"] == "test.txt"
    assert "content" not in args


@pytest.mark.asyncio
async def test_openai_nested_json_fallback(agent):
    """Test unwrapping of OpenAI 'function' object encapsulation."""
    message = """Here is the call:
<tool_call>
{
    "function": {
        "name": "run_python",
        "arguments": {"code": "print(1)"}
    }
}
</tool_call>"""
    agent.context.llm_client.chat_completion = AsyncMock(side_effect=[
        {"choices": [{"message": {"content": message}}]},
        {"choices": [{"message": {"content": "I am done."}}]}
    ])
    
    background_tasks = MagicMock()
    body = {"messages": [{"role": "user", "content": "please run the tool"}]}
    
    with patch("ghost_agent.core.agent.get_active_tool_definitions", return_value=[{"function": {"name": "run_python"}}]):
        await agent.handle_chat(body, background_tasks)
        
    tool_calls = body['messages'][2].get('tool_calls', [])
    assert len(tool_calls) == 1
    assert tool_calls[0]["function"]["name"] == "run_python"
    args = json.loads(tool_calls[0]["function"]["arguments"])
    assert args["code"] == "print(1)"


@pytest.mark.asyncio
async def test_hallucinated_arguments_wrapper(agent):
    """Test unwrapping of 'arguments' or 'parameters' wrapper dict."""
    message = """<tool_call>
{"name": "run_python", "arguments": {"parameters": {"code": "print(2)"}}}
</tool_call>"""
    agent.context.llm_client.chat_completion = AsyncMock(side_effect=[
        {"choices": [{"message": {"content": message}}]},
        {"choices": [{"message": {"content": "I am done."}}]}
    ])
    
    background_tasks = MagicMock()
    body = {"messages": [{"role": "user", "content": "please run the tool"}]}
    
    with patch("ghost_agent.core.agent.get_active_tool_definitions", return_value=[{"function": {"name": "run_python"}}]):
        await agent.handle_chat(body, background_tasks)
        
    tool_calls = body['messages'][2].get('tool_calls', [])
    assert len(tool_calls) == 1
    assert tool_calls[0]["function"]["name"] == "run_python"
    args = json.loads(tool_calls[0]["function"]["arguments"])
    assert args["code"] == "print(2)"
