import asyncio
import datetime
import json
import secrets
import shutil
import uuid
import httpx
import os
import io
import zipfile
from pathlib import Path
from fastapi import APIRouter, Request, BackgroundTasks, Security, HTTPException, Depends, Response, UploadFile, File
from fastapi.responses import StreamingResponse, JSONResponse, FileResponse
from fastapi.security.api_key import APIKeyHeader
from ..utils.helpers import get_utc_timestamp
import logging
from ..utils.logging import Icons, pretty_log

logger = logging.getLogger("GhostAgent")

router = APIRouter()


def _log_internal_error(context_label: str) -> str:
    """Log the current exception under a short correlation id and return the
    id. The wire response gets only the id — never the raw exception text —
    so a malformed-input repro can't reveal internal paths / URLs / Python
    error internals to the client."""
    eid = uuid.uuid4().hex[:8]
    logger.error("[err_id=%s] internal error in %s", eid, context_label, exc_info=True)
    return eid

API_KEY_NAME = "X-Ghost-Key"
api_key_header = APIKeyHeader(name=API_KEY_NAME, auto_error=False)

def _mark_foreground(agent, delta: int) -> None:
    """Adjust the llm client's active-user-request counter (see
    LLMClient.foreground_requests — it parks background LLM work for the
    whole life of a user request, not just per LLM call). Tolerant of
    mocked/missing clients: instrumentation must never break a request,
    so it only touches a counter that is actually an int."""
    try:
        llm = getattr(getattr(agent, "context", None), "llm_client", None)
        cur = getattr(llm, "foreground_requests", None)
        if isinstance(cur, int):
            llm.foreground_requests = max(0, cur + delta)
    except Exception:
        pass


def get_agent(request: Request):
    return request.app.state.agent

async def verify_api_key(request: Request, api_key: str = Security(api_key_header)):
    agent = get_agent(request)
    configured = agent.context.args.api_key
    if configured:
        # Constant-time comparison to avoid a timing side-channel that
        # could let an attacker recover the key byte-by-byte. Compare as
        # BYTES: compare_digest raises TypeError on a non-ASCII str, which
        # would surface as a 500 (and a logged traceback) instead of a clean
        # 403 for an attacker-controlled header value.
        _supplied = str(api_key or "").encode("utf-8", "ignore")
        _expected = str(configured).encode("utf-8", "ignore")
        if not api_key or not secrets.compare_digest(_supplied, _expected):
            # Surface auth failures on the monitored stream (brute-force /
            # misconfigured client). Never log the key bytes.
            pretty_log("Auth Rejected", f"path={request.url.path}",
                       icon=Icons.SHIELD, level="WARNING")
            raise HTTPException(status_code=403, detail="Invalid API Key")
    return api_key

@router.get("/")
async def root_check():
    return Response(content="Ollama is running", media_type="text/plain")

@router.head("/")
async def root_head():
    return Response(content="OK", media_type="text/plain")

@router.get("/api/version")
async def api_version():
    return {"version": "0.1.24"}

@router.post("/api/show")
async def api_show(request: Request):
    return {
        "modelfile": "# Modelfile generated by Ghost Agent\nFROM ghost-model",
        "parameters": "stop \"<|im_start|>\"\nstop \"<|im_end|>\"",
        "template": "<|im_start|>system\n{{ .System }}<|im_end|>\n<|im_start|>user\n{{ .Prompt }}<|im_end|>\n<|im_start|>assistant\n",
        "details": {
            "format": "gguf", "family": "qwen3", "families": ["qwen3"], "parameter_size": "35B-A3B", "quantization_level": "Q4_0"
        }
    }

@router.get("/api/tags")
async def list_models(request: Request):
    model_name = request.app.state.args.model
    return {
        "models": [
            {
                "name": model_name, "model": model_name, "modified_at": get_utc_timestamp(),
                "size": 1000000000, "digest": "sha256:qwen-3.6-35b-a3",
                "details": {"format": "gguf", "family": "qwen3", "families": ["qwen3"], "parameter_size": "35B-A3B", "quantization_level": "Q4_0"}
            }
        ]
    }

@router.get("/v1/models", dependencies=[Security(verify_api_key)])
async def list_openai_models(request: Request):
    model_name = request.app.state.args.model
    return {
        "object": "list",
        "data": [
            {"id": model_name, "object": "model", "created": int(datetime.datetime.now().timestamp()), "owned_by": "ghost-system"}
        ]
    }

@router.post("/api/pull")
async def api_pull(request: Request):
    return {"status": "success"}

@router.delete("/api/delete", dependencies=[Security(verify_api_key)])
async def api_delete(request: Request):
    # Ollama-compatible: DELETE /api/delete removes a pulled model. We
    # serve a single canonical model and never let the user actually
    # delete it, but returning 200/success for ANY name was misleading —
    # clients couldn't distinguish "deleted my model" from "no such
    # model." Validate against the configured model name.
    try:
        body = await request.json()
    except (json.JSONDecodeError, ValueError, UnicodeDecodeError):
        body = {}
    name = (body or {}).get("model") or (body or {}).get("name")
    configured = request.app.state.args.model
    if name and name != configured:
        return JSONResponse(
            {"error": {"message": f"model '{name}' not found", "type": "NotFound"}},
            status_code=404,
        )
    return {"status": "success"}

@router.post("/api/generate", dependencies=[Security(verify_api_key)])
async def api_generate(request: Request):
    agent = get_agent(request)
    try:
        body = await request.json()
    except (json.JSONDecodeError, ValueError, UnicodeDecodeError) as e:
        return JSONResponse({"error": f"Invalid JSON: {e}"}, 400)

    prompt = body.get("prompt", "")
    model = body.get("model", "default")
    stream = body.get("stream", False)

    # Always request a non-streaming upstream completion: this handler
    # parses the body with resp.json(), and the local "stream" emulation
    # below sends the full response as a single NDJSON frame anyway.
    # Forwarding stream=True made the upstream return SSE frames, so
    # resp.json() raised and every Ollama-style streaming client got a 500.
    chat_payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "stream": False
    }

    try:
        resp = await agent.context.llm_client.http_client.post("/v1/chat/completions", json=chat_payload)
        resp.raise_for_status()
        llm_resp = resp.json()
        content = llm_resp["choices"][0]["message"]["content"]
    except Exception:
        _eid = _log_internal_error("api_generate")
        return JSONResponse({"error": f"internal error (error_id={_eid})"}, 500)

    if stream:
         async def generator():
             yield json.dumps({
                 "model": model,
                 "created_at": get_utc_timestamp(),
                 "response": content,
                 "done": True
             }).encode('utf-8') + b"\n"
         return StreamingResponse(generator(), media_type="application/x-ndjson")
    else:
        return {
            "model": model,
            "created_at": get_utc_timestamp(),
            "response": content,
            "done": True
        }

@router.post("/chat", dependencies=[Security(verify_api_key)])
@router.post("/v1/chat/completions", dependencies=[Security(verify_api_key)])
@router.post("/api/chat", dependencies=[Security(verify_api_key)])
async def chat_proxy(request: Request, background_tasks: BackgroundTasks):
    agent = get_agent(request)
    # Body parse failures used to bubble up as a raw 500 with no JSON
    # payload — clients then saw an HTML error page instead of a
    # parseable error. Wrap the parse so malformed JSON / empty body
    # produces an OpenAI-shaped error JSON with a 400 status, matching
    # the error contract the rest of the route already provides for
    # handler exceptions.
    try:
        body = await request.json()
    except (json.JSONDecodeError, ValueError, UnicodeDecodeError) as e:
        return JSONResponse(
            {
                "error": {
                    "message": f"Invalid JSON in request body: {e}",
                    "type": type(e).__name__,
                }
            },
            status_code=400,
        )
    if not isinstance(body, dict):
        return JSONResponse(
            {
                "error": {
                    "message": (
                        "Request body must be a JSON object, got "
                        f"{type(body).__name__}"
                    ),
                    "type": "InvalidRequestShape",
                }
            },
            status_code=400,
        )

    # ---- request validation (HTTP boundary) ---------------------------
    # Stops three classes of garbage from reaching `agent.handle_chat`:
    #   1. `messages: []` (or missing) — used to silently produce
    #      fabricated content from injected system state.
    #   2. `messages: "not a list"` / each-message-not-a-dict — used to
    #      crash `handle_chat` with `'str' object has no attribute 'get'`
    #      leaking Python internals as a 500.
    #   3. Unknown role values — passed through to the upstream LLM and
    #      surfaced as an "upstream error 400 template parser failed"
    #      string masquerading as an assistant reply.
    # Errors here are 422 with OpenAI-style `{error:{message,type}}`.
    messages = body.get("messages")
    if not isinstance(messages, list) or not messages:
        return JSONResponse(
            {"error": {
                "message": "`messages` must be a non-empty list of message objects",
                "type": "InvalidRequestShape",
            }},
            status_code=422,
        )
    allowed_roles = {"system", "user", "assistant", "tool", "function"}
    for i, m in enumerate(messages):
        if not isinstance(m, dict):
            return JSONResponse(
                {"error": {
                    "message": f"messages[{i}] must be an object, got {type(m).__name__}",
                    "type": "InvalidRequestShape",
                }},
                status_code=422,
            )
        role = m.get("role")
        if role not in allowed_roles:
            return JSONResponse(
                {"error": {
                    "message": (
                        f"messages[{i}].role={role!r} is not one of "
                        f"{sorted(allowed_roles)}"
                    ),
                    "type": "InvalidRequestShape",
                }},
                status_code=422,
            )

        # Content shape. `null`/absent content is valid ONLY on an assistant
        # message that carries tool_calls (the standard tool-calling turn).
        # Everywhere else a message with no usable content used to slip
        # through to the agent, which then fabricates a reply from nothing
        # (e.g. a `user` turn with content=null produced a greeting instead
        # of a 422). Reject null / wrong-typed / empty-user content here.
        content = m.get("content")
        if content is None:
            if not (role == "assistant" and m.get("tool_calls")):
                return JSONResponse(
                    {"error": {
                        "message": (
                            f"messages[{i}].content is required (null is allowed "
                            "only on an assistant message with tool_calls)"
                        ),
                        "type": "InvalidRequestShape",
                    }},
                    status_code=422,
                )
        elif not isinstance(content, (str, list)):
            return JSONResponse(
                {"error": {
                    "message": (
                        f"messages[{i}].content must be a string or list, got "
                        f"{type(content).__name__}"
                    ),
                    "type": "InvalidRequestShape",
                }},
                status_code=422,
            )
        elif role == "user" and isinstance(content, str) and not content.strip():
            return JSONResponse(
                {"error": {
                    "message": f"messages[{i}].content is empty; a user message must carry content",
                    "type": "InvalidRequestShape",
                }},
                status_code=422,
            )

    # `model` is optional in many clients (Ollama leaves it implicit).
    # If supplied AND it doesn't match the configured model, return 404
    # rather than silently rerouting to the upstream. We don't 404 a
    # missing key — that preserves Ollama compatibility.
    requested_model = body.get("model")
    configured_model = agent.context.args.model
    if requested_model and requested_model != configured_model:
        return JSONResponse(
            {"error": {
                "message": (
                    f"model {requested_model!r} not found; configured "
                    f"model is {configured_model!r}"
                ),
                "type": "ModelNotFound",
            }},
            status_code=404,
        )
    model = requested_model or configured_model
    stream = body.get("stream", False)
    
    # Extract Request ID if provided (for Slack Bot correlation)
    request_id = request.headers.get("X-Request-ID")
    
    if stream:
        headers = {
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
        
        async def stream_generator():
            # Track whether any real content chunk has shipped to the
            # client. If yes, an additional `delta.content` error chunk
            # would APPEND to the partial response the user already
            # sees — "Here is the answ" + "CRITICAL SERVER ERROR:
            # ConnectionResetError" mashed together. Once content has
            # started, the `event: error` SSE frame is enough for
            # programmatic detection; emitting an extra content chunk
            # corrupts the visible reply.
            content_started = False
            # Mark a user request active for its WHOLE lifecycle (agent
            # loop + final-answer streaming) so background LLM work parks
            # instead of stealing the inference slot between this
            # request's tool calls. See LLMClient.foreground_requests.
            _mark_foreground(agent, +1)
            try:
                # Yield an SSE comment to send HTTP headers instantly and keep reverse proxies alive
                yield b": processing request...\n\n"

                content, created_time, req_id = await agent.handle_chat(body, background_tasks, request_id=request_id)

                if hasattr(content, '__aiter__'):
                    async for chunk in content:
                        content_started = True
                        yield chunk
                else:
                    async for chunk in agent.context.llm_client.stream_openai(model, content, created_time, req_id):
                        content_started = True
                        yield chunk
            except Exception as e:
                # Opaque error id on the wire (matches the non-streaming path) —
                # the raw str(e) leaked upstream URLs / file paths / Python
                # internals to the client on the DEFAULT (streaming) chat path.
                _eid = _log_internal_error("chat_proxy (streaming)")
                err_msg = f"internal server error (error_id={_eid})"
                error_event = {"error": {"message": err_msg, "type": "InternalError"}}
                yield f"event: error\ndata: {json.dumps(error_event)}\n\n".encode('utf-8')
                # Only emit a content chunk for visual display when
                # NO content has streamed yet — otherwise it gets
                # concatenated to the partial reply the client has
                # already rendered.
                if not content_started:
                    yield f"data: {json.dumps({'choices': [{'delta': {'content': err_msg}}]})}\n\n".encode('utf-8')
                yield b"data: [DONE]\n\n"
                return
            finally:
                _mark_foreground(agent, -1)

        return StreamingResponse(stream_generator(), media_type="text/event-stream", headers=headers)
    
    # Non-streaming fallback. Any exception in handle_chat used to bubble
    # up as a raw 500 with no JSON body — clients then saw an HTML error
    # page instead of a parseable error. Mirror the streaming path's
    # error-shape (OpenAI-style ``error.message``/``error.type``) so the
    # Slack bot and web UI can render a useful message to the user.
    _mark_foreground(agent, +1)
    try:
        content, created_time, req_id = await agent.handle_chat(body, background_tasks, request_id=request_id)
    except Exception as e:
        # The detailed stack lives in the log. The wire response gets a
        # generic message + an opaque exception type so a malformed-body
        # repro doesn't reveal Python internals (e.g. "'str' object has
        # no attribute 'get'"). The error-id lets you correlate to logs.
        err_id = uuid.uuid4().hex[:8]
        logger.error(
            f"[err_id={err_id}] Non-streaming error in chat_proxy: "
            f"{type(e).__name__}: {e}",
            exc_info=True,
        )
        return JSONResponse(
            {
                "error": {
                    "message": (
                        "internal error while handling chat request "
                        f"(error_id={err_id})"
                    ),
                    "type": "InternalError",
                }
            },
            status_code=500,
        )
    finally:
        _mark_foreground(agent, -1)

    return JSONResponse({
        "id": f"chatcmpl-{req_id}", "object": "chat.completion", "created": created_time, "model": model,
        "choices": [{"index": 0, "message": {"role": "assistant", "content": content}, "finish_reason": "stop"}],
        "message": {"role": "assistant", "content": content},
        "done": True, "created_at": get_utc_timestamp()
    })

@router.post("/api/workspace/save", dependencies=[Security(verify_api_key)])
async def save_workspace(request: Request):
    """Packages the current chat history, scratchpad, and sandbox into a downloadable zip."""
    agent = get_agent(request)
    # Empty / malformed body used to surface as a bare 500
    # `Internal Server Error` with no JSON envelope. Accept "no body"
    # as "save with empty chat history" and reject malformed bodies
    # with a structured 400.
    raw = await request.body()
    if not raw:
        body = {}
    else:
        try:
            body = json.loads(raw)
        except (json.JSONDecodeError, ValueError, UnicodeDecodeError) as e:
            return JSONResponse(
                {"error": {"message": f"Invalid JSON in request body: {e}",
                           "type": type(e).__name__}},
                status_code=400,
            )
        if not isinstance(body, dict):
            return JSONResponse(
                {"error": {"message": f"Request body must be a JSON object, got {type(body).__name__}",
                           "type": "InvalidRequestShape"}},
                status_code=400,
            )
    chat_history = body.get("chat_history", [])

    # The previous version used `iter([zip_buffer.getvalue()])` which held
    # the ENTIRE compressed zip in memory as one bytes object — fine for
    # tiny workspaces, a memory spike for big ones. Stream from the buffer
    # in chunks instead, and explicitly close it in finally.
    zip_buffer = io.BytesIO()
    try:
        with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
            session_data = {
                "chat_history": chat_history,
                "scratchpad": dict(agent.context.scratchpad._data) if getattr(agent.context, 'scratchpad', None) else {}
            }
            zip_file.writestr("session.json", json.dumps(session_data, indent=2))

            sandbox_dir = agent.context.sandbox_dir
            for root, dirs, files in os.walk(sandbox_dir):
                if "acquired_skills" in Path(root).parts:
                    continue
                for file_name in files:
                    file_path = Path(root) / file_name
                    arcname = file_path.relative_to(sandbox_dir)
                    zip_file.write(file_path, f"sandbox/{arcname}")

        zip_buffer.seek(0)
        filename = f"workspace_{get_utc_timestamp().replace(':', '')}.zip"

        # Take the bytes once, close the buffer, then stream chunks. The
        # buffer's memory is reclaimed as soon as the inner generator
        # finishes. (Holding the bytes in a local var means the BytesIO
        # itself can be closed immediately after.)
        zip_bytes = zip_buffer.getvalue()
    finally:
        zip_buffer.close()

    async def _stream_chunks():
        try:
            CHUNK = 64 * 1024
            for i in range(0, len(zip_bytes), CHUNK):
                yield zip_bytes[i:i + CHUNK]
        finally:
            # Drop the local reference so GC can reclaim the buffer.
            pass

    return StreamingResponse(
        _stream_chunks(),
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )

_MAX_UPLOAD_BYTES = 100 * 1024 * 1024  # 100 MB hard ceiling on inbound uploads


def _is_within(base: Path, candidate: Path) -> bool:
    """True iff resolved ``candidate`` is ``base`` or strictly inside it.

    Robust against the prefix-``startswith`` sibling-directory bypass (e.g.
    ``/data/sandbox`` matching ``/data/sandbox_evil``) that a bare
    ``str(p).startswith(str(base))`` check allows.
    """
    try:
        candidate.resolve().relative_to(base.resolve())
        return True
    except (ValueError, OSError):
        return False


async def _read_capped(upload: UploadFile) -> bytes:
    """Read an UploadFile body with a hard size cap. Without this, a
    multi-GB upload exhausts memory and disk.

    Chunks must be `bytes`/`bytearray`. Test fixtures often pass
    `MagicMock(spec=UploadFile)` whose `read()` returns a MagicMock — that
    MagicMock has `__len__` defaulting to 0, so a naive byte-counting
    loop would never terminate. We require real bytes and additionally
    cap iterations as a belt-and-braces guard.
    """
    total = 0
    chunks: list[bytes] = []
    max_iters = (_MAX_UPLOAD_BYTES // 65536) + 32
    for _ in range(max_iters):
        chunk = await upload.read(65536)
        if not chunk:
            break
        if not isinstance(chunk, (bytes, bytearray)):
            raise HTTPException(
                status_code=400,
                detail=f"Upload returned non-bytes chunk ({type(chunk).__name__})",
            )
        total += len(chunk)
        if total > _MAX_UPLOAD_BYTES:
            raise HTTPException(
                status_code=413,
                detail=f"Upload exceeds {_MAX_UPLOAD_BYTES // (1024*1024)} MB cap",
            )
        chunks.append(bytes(chunk))
    else:
        raise HTTPException(
            status_code=413,
            detail="Upload iteration cap exceeded — refusing pathological producer.",
        )
    return b"".join(chunks)


@router.post("/api/workspace/load", dependencies=[Security(verify_api_key)])
async def load_workspace(request: Request, file: UploadFile = File(...)):
    """Restores a workspace by cleaning the sandbox and unpacking the provided zip."""
    agent = get_agent(request)
    sandbox_dir = agent.context.sandbox_dir.resolve()
    zip_bytes = await _read_capped(file)
    # Uncompressed-output ceiling — the 100 MB _read_capped bound is on the
    # COMPRESSED input; without this a ~100 MB zip-of-zeroes inflates to tens
    # of GB and OOMs the process / fills the disk (decompression bomb).
    _MAX_UNCOMPRESSED = 500 * 1024 * 1024

    try:
        with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as zip_ref:
            # VALIDATE FIRST, wipe second. Previously the sandbox was cleared
            # before session.json was parsed, so a malformed session.json (or
            # any mid-extraction error) destroyed the workspace with no
            # rollback. Do all fallible parsing/size-checking up front.
            total_uncompressed = sum(max(0, zi.file_size) for zi in zip_ref.infolist())
            if total_uncompressed > _MAX_UNCOMPRESSED:
                raise HTTPException(
                    status_code=413,
                    detail=f"Archive inflates to {total_uncompressed // (1024*1024)} MB; "
                           f"cap is {_MAX_UNCOMPRESSED // (1024*1024)} MB.",
                )
            session_data = None
            for zip_info in zip_ref.infolist():
                if zip_info.filename == "session.json":
                    try:
                        session_data = json.loads(zip_ref.read(zip_info.filename).decode("utf-8"))
                    except (ValueError, UnicodeDecodeError):
                        raise HTTPException(status_code=400, detail="session.json is not valid JSON")
                    break

            # 1. Clear sandbox safely (Preserve permanent skills) — only AFTER
            # the archive validated above.
            for item in sandbox_dir.iterdir():
                if item.name == "acquired_skills":
                    continue
                if item.is_dir():
                    shutil.rmtree(item, ignore_errors=True)
                else:
                    item.unlink(missing_ok=True)

            # 2. Restore session state.
            chat_history = []
            if session_data is not None:
                chat_history = session_data.get("chat_history", [])
                scratchpad_data = session_data.get("scratchpad", {})
                if getattr(agent.context, 'scratchpad', None):
                    agent.context.scratchpad.clear()
                    if isinstance(scratchpad_data, dict):
                        for k, v in scratchpad_data.items():
                            agent.context.scratchpad.set(k, v)

            # 3. Extract files.
            for zip_info in zip_ref.infolist():
                if not zip_info.filename.startswith("sandbox/"):
                    continue
                rel_path = zip_info.filename[len("sandbox/"):]
                if not rel_path:
                    continue
                extracted_path = (sandbox_dir / rel_path).resolve()
                # Prevent zip-slip traversal (relative_to-based; rejects
                # sibling-dir prefix escapes).
                if not _is_within(sandbox_dir, extracted_path):
                    continue
                if zip_info.is_dir():
                    extracted_path.mkdir(parents=True, exist_ok=True)
                else:
                    extracted_path.parent.mkdir(parents=True, exist_ok=True)
                    extracted_path.write_bytes(zip_ref.read(zip_info.filename))

        return {"status": "success", "chat_history": chat_history}
    except HTTPException:
        raise
    except zipfile.BadZipFile:
        raise HTTPException(status_code=400, detail="Invalid zip file format")
    except Exception:
        # Don't leak internal exception text to the client.
        _eid = _log_internal_error("workspace/load")
        raise HTTPException(status_code=500, detail=f"Workspace load failed (error id {_eid}).")

@router.post("/api/memory/correct", dependencies=[Security(verify_api_key)])
async def memory_correct(request: Request):
    """Surgically rewrite ONE vector-memory fragment's text.

    The safe path for fixing a poisoned auto-memory: Chroma's persist dir
    must only ever be touched by the process that owns it (a second
    PersistentClient risks HNSW corruption), so the correction runs
    in-process via VectorMemory.correct_fragment. Body:
    {"match": <exact text or unique substring>, "replacement": <new text>}.
    """
    agent = get_agent(request)
    try:
        body = await request.json()
    except (json.JSONDecodeError, ValueError, UnicodeDecodeError) as e:
        return JSONResponse({"error": f"Invalid JSON: {e}"}, 400)
    match = str(body.get("match") or "")
    replacement = str(body.get("replacement") or "")
    memory = getattr(getattr(agent, "context", None), "memory_system", None)
    if memory is None or not hasattr(memory, "correct_fragment"):
        return JSONResponse({"error": "memory system unavailable"}, 503)
    ok, detail = memory.correct_fragment(match, replacement)
    if not ok:
        return JSONResponse({"ok": False, "error": detail}, 409)
    return {"ok": True, **detail}


@router.post("/api/memory/delete", dependencies=[Security(verify_api_key)])
async def memory_delete(request: Request):
    """Surgically DELETE one vector-memory fragment.

    Companion to /api/memory/correct for a fragment that is WHOLLY false
    (nothing true to rewrite it into). Runs in-process for the same reason
    (a second PersistentClient against the live Chroma dir risks HNSW
    corruption). Body: {"match": <exact text or unique substring>}.
    """
    agent = get_agent(request)
    try:
        body = await request.json()
    except (json.JSONDecodeError, ValueError, UnicodeDecodeError) as e:
        return JSONResponse({"error": f"Invalid JSON: {e}"}, 400)
    match = str(body.get("match") or "")
    memory = getattr(getattr(agent, "context", None), "memory_system", None)
    if memory is None or not hasattr(memory, "delete_fragment"):
        return JSONResponse({"error": "memory system unavailable"}, 503)
    ok, detail = memory.delete_fragment(match)
    if not ok:
        return JSONResponse({"ok": False, "error": detail}, 409)
    return {"ok": True, **detail}


@router.post("/api/upload", dependencies=[Security(verify_api_key)])
async def upload_file(request: Request, file: UploadFile = File(...)):
    agent = get_agent(request)
    # When a project is active, land the upload in its scoped dir so it joins
    # the working set the model sees and the (scoped) file_system can read it.
    from ..tools.file_system import project_scoped_sandbox
    sandbox_dir = project_scoped_sandbox(agent.context)[0]
    # Reject path traversal AND the absent-filename case explicitly.
    if not file.filename or ".." in file.filename or file.filename.startswith("/"):
        raise HTTPException(status_code=400, detail="Invalid filename")
    file_path = (sandbox_dir / file.filename).resolve()
    if not _is_within(sandbox_dir, file_path):
        raise HTTPException(status_code=400, detail="Invalid filename")

    # Read with size cap before writing — same DoS guard as workspace/load.
    body = await _read_capped(file)

    def _write_file():
        with open(file_path, "wb") as buffer:
            buffer.write(body)
    await asyncio.to_thread(_write_file)
    return {"status": "success", "filename": file.filename}

@router.get("/api/download/{filename:path}", dependencies=[Security(verify_api_key)])
async def download_file(request: Request, filename: str):
    agent = get_agent(request)
    sandbox_dir = agent.context.sandbox_dir
    # Reject traversal explicitly (parity with /api/upload) then containment-check.
    if ".." in filename or filename.startswith("/"):
        raise HTTPException(status_code=404, detail="File not found")
    file_path = (sandbox_dir / filename).resolve()
    # Fallback: when a project is active, artefact tools (image_generation,
    # execute-saved plots) write into <sandbox>/projects/<id>/, but the model
    # often emits a BARE link (`/api/download/plot.png`). If the bare path
    # isn't at the root, retry under the active project's scoped dir so the
    # link still resolves. Containment is re-checked below.
    if not file_path.exists() and "/" not in filename:
        pid = getattr(agent.context, "current_project_id", None)
        if isinstance(pid, str) and pid.strip():
            cand = (sandbox_dir / "projects" / pid.strip().lower() / filename).resolve()
            if _is_within(sandbox_dir, cand) and cand.exists():
                file_path = cand
    if not _is_within(sandbox_dir, file_path) or not file_path.exists():
        raise HTTPException(status_code=404, detail="File not found")
    return FileResponse(path=str(file_path), filename=file_path.name)

@router.api_route("/{path:path}", methods=["GET", "POST", "PUT", "DELETE", "HEAD", "OPTIONS"], dependencies=[Security(verify_api_key)])
async def catch_all(request: Request, path: str):
    agent = get_agent(request)
    url = f"/{path}"
    headers = dict(request.headers)
    headers.pop("host", None)
    headers.pop("content-length", None)

    # Sniff whether this is a streaming/SSE request so we can set the right
    # response media type AND disable buffering on intermediate proxies.
    # Without `X-Accel-Buffering: no`, nginx (and any sane reverse proxy)
    # will buffer SSE chunks — the client sees the stream arrive in one
    # batch at the end instead of in real time.
    body_says_stream = False
    try:
        # Best-effort peek at the JSON body. The body has not been read yet
        # because we forward `request.stream()` straight to the upstream
        # client below; once we call `await request.body()` here the stream
        # is exhausted, so we re-feed it to httpx via `content=...`.
        if request.method in ("POST", "PUT") and "json" in request.headers.get("content-type", "").lower():
            raw = await request.body()
            if raw:
                try:
                    parsed = json.loads(raw)
                    if isinstance(parsed, dict) and parsed.get("stream") is True:
                        body_says_stream = True
                except (json.JSONDecodeError, ValueError):
                    pass
            forward_content = raw
        else:
            forward_content = request.stream()
    except Exception:
        forward_content = request.stream()

    try:
        req = agent.context.llm_client.http_client.build_request(
            request.method, url, headers=headers, content=forward_content
        )
        r = await agent.context.llm_client.http_client.send(req, stream=True)

        upstream_ct = r.headers.get("content-type", "") or ""
        is_event_stream = "text/event-stream" in upstream_ct.lower() or body_says_stream

        async def stream_generator():
            try:
                async for chunk in r.aiter_bytes():
                    yield chunk
            finally:
                await r.aclose()

        response_headers = {}
        if is_event_stream:
            # Tell nginx / any reverse proxy NOT to buffer this response.
            response_headers["X-Accel-Buffering"] = "no"
            response_headers["Cache-Control"] = "no-cache"

        return StreamingResponse(
            stream_generator(),
            status_code=r.status_code,
            media_type=("text/event-stream" if is_event_stream else upstream_ct or None),
            headers=response_headers,
        )
    except Exception as e:
        pretty_log("Proxy Failed", f"{request.method} /{path}: {type(e).__name__}: {e}",
                   icon=Icons.FAIL, level="ERROR")
        return JSONResponse({"error": f"Proxy Error: {e}"}, 502)