import asyncio
import datetime
import json
import shutil
import uuid
import httpx
from fastapi import APIRouter, Request, BackgroundTasks, Security, HTTPException, Depends, Response, UploadFile, File
from fastapi.responses import StreamingResponse, JSONResponse, FileResponse
from fastapi.security.api_key import APIKeyHeader
from ..utils.helpers import get_utc_timestamp
from ..utils.logging import Icons, pretty_log

router = APIRouter()

API_KEY_NAME = "X-Ghost-Key"
api_key_header = APIKeyHeader(name=API_KEY_NAME, auto_error=False)

def clear_global_history():
    """
    Placeholder for stateful history clearing. 
    Current implementation is stateless (OpenAI-compatible).
    """
    return True

def get_agent(request: Request):
    return request.app.state.agent

async def verify_api_key(request: Request, api_key: str = Security(api_key_header)):
    agent = get_agent(request)
    if agent.context.args.api_key and (not api_key or api_key != agent.context.args.api_key):
        raise HTTPException(status_code=403, detail="Invalid API Key")
    return api_key

@router.get("/")
async def root_check():
    return Response(content="Ollama is running", media_type="text/plain")

@router.head("/")
async def root_head():
    return Response(content="OK", media_type="text/plain")

@router.get("/api/version")
async def api_version():
    return {"version": "0.1.24"}

@router.post("/api/show")
async def api_show(request: Request):
    return {
        "modelfile": "# Modelfile generated by Ghost Agent\nFROM ghost-model",
        "parameters": "stop \"<|im_start|>\"\nstop \"<|im_end|>\"",
        "template": "<|im_start|>system\n{{ .System }}<|im_end|>\n<|im_start|>user\n{{ .Prompt }}<|im_end|>\n<|im_start|>assistant\n",
        "details": {
            "format": "gguf", "family": "qwen2", "families": ["qwen2"], "parameter_size": "9B", "quantization_level": "Q4_0"
        }
    }

@router.get("/api/tags")
async def list_models(request: Request):
    model_name = request.app.state.args.model
    return {
        "models": [
            {
                "name": model_name, "model": model_name, "modified_at": get_utc_timestamp(),
                "size": 1000000000, "digest": "sha256:qwen-3.5-9b",
                "details": {"format": "gguf", "family": "qwen2", "families": ["qwen2"], "parameter_size": "9B", "quantization_level": "Q4_0"}
            }
        ]
    }

@router.get("/v1/models", dependencies=[Security(verify_api_key)])
async def list_openai_models(request: Request):
    model_name = request.app.state.args.model
    return {
        "object": "list",
        "data": [
            {"id": model_name, "object": "model", "created": int(datetime.datetime.now().timestamp()), "owned_by": "ghost-system"}
        ]
    }

@router.post("/api/pull")
async def api_pull(request: Request):
    return {"status": "success"}

@router.delete("/api/delete")
async def api_delete(request: Request):
    return {"status": "success"}

@router.post("/api/generate", dependencies=[Security(verify_api_key)])
async def api_generate(request: Request):
    agent = get_agent(request)
    try: body = await request.json()
    except: return JSONResponse({"error": "Invalid JSON"}, 400)

    prompt = body.get("prompt", "")
    model = body.get("model", "default")
    stream = body.get("stream", False)

    chat_payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "stream": stream
    }

    try:
        resp = await agent.context.llm_client.http_client.post("/v1/chat/completions", json=chat_payload)
        resp.raise_for_status()
        llm_resp = resp.json()
        content = llm_resp["choices"][0]["message"]["content"]
    except Exception as e:
        return JSONResponse({"error": str(e)}, 500)

    if stream:
         async def generator():
             yield json.dumps({
                 "model": model,
                 "created_at": get_utc_timestamp(),
                 "response": content,
                 "done": True
             }).encode('utf-8') + b"\n"
         return StreamingResponse(generator(), media_type="application/x-ndjson")
    else:
        return {
            "model": model,
            "created_at": get_utc_timestamp(),
            "response": content,
            "done": True
        }

@router.post("/chat", dependencies=[Security(verify_api_key)])
@router.post("/v1/chat/completions", dependencies=[Security(verify_api_key)])
@router.post("/api/chat", dependencies=[Security(verify_api_key)])
async def chat_proxy(request: Request, background_tasks: BackgroundTasks):
    agent = get_agent(request)
    body = await request.json()
    model = body.get("model", agent.context.args.model)
    stream = body.get("stream", False)
    
    # Extract Request ID if provided (for Slack Bot correlation)
    request_id = request.headers.get("X-Request-ID")
    
    if stream:
        headers = {
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
        
        async def stream_generator():
            try:
                # Yield an SSE comment to send HTTP headers instantly and keep reverse proxies alive
                yield b": processing request...\n\n"
                
                content, created_time, req_id = await agent.handle_chat(body, background_tasks, request_id=request_id)
                
                if hasattr(content, '__aiter__'):
                    async for chunk in content:
                        yield chunk
                else:
                    async for chunk in agent.context.llm_client.stream_openai(model, content, created_time, req_id):
                        yield chunk
            except Exception as e:
                import traceback
                traceback.print_exc()
                err_msg = f"\\n\\nCRITICAL SERVER ERROR: {str(e)}"
                yield f"data: {json.dumps({'choices': [{'delta': {'content': err_msg}}]})}\\n\\n".encode('utf-8')
                yield b"data: [DONE]\\n\\n"
                # Do NOT raise e here: raising causes Uvicorn to drop the HTTP connection immediately,
                # preventing the client from receiving the trailing chunks and resulting in "Response ended prematurely"
                return

        return StreamingResponse(stream_generator(), media_type="text/event-stream", headers=headers)
    
    # Non-streaming fallback
    content, created_time, req_id = await agent.handle_chat(body, background_tasks, request_id=request_id)
    
    return JSONResponse({
        "id": f"chatcmpl-{req_id}", "object": "chat.completion", "created": created_time, "model": model,
        "choices": [{"index": 0, "message": {"role": "assistant", "content": content}, "finish_reason": "stop"}],
        "message": {"role": "assistant", "content": content},
        "done": True, "created_at": get_utc_timestamp()
    })

@router.post("/api/upload", dependencies=[Security(verify_api_key)])
async def upload_file(request: Request, file: UploadFile = File(...)):
    agent = get_agent(request)
    sandbox_dir = agent.context.sandbox_dir
    file_path = (sandbox_dir / file.filename).resolve()
    if not str(file_path).startswith(str(sandbox_dir.resolve())):
        raise HTTPException(status_code=400, detail="Invalid filename")
    def _write_file():
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
    await asyncio.to_thread(_write_file)
    return {"status": "success", "filename": file.filename}

@router.get("/api/download/{filename:path}", dependencies=[Security(verify_api_key)])
async def download_file(request: Request, filename: str):
    agent = get_agent(request)
    sandbox_dir = agent.context.sandbox_dir
    file_path = (sandbox_dir / filename).resolve()
    if not str(file_path).startswith(str(sandbox_dir.resolve())) or not file_path.exists():
        raise HTTPException(status_code=404, detail="File not found")
    return FileResponse(path=str(file_path), filename=file_path.name)

@router.api_route("/{path:path}", methods=["GET", "POST", "PUT", "DELETE", "HEAD", "OPTIONS"], dependencies=[Security(verify_api_key)])
async def catch_all(request: Request, path: str):
    agent = get_agent(request)
    url = f"/{path}"
    headers = dict(request.headers)
    headers.pop("host", None)
    headers.pop("content-length", None) 

    try:
        req = agent.context.llm_client.http_client.build_request(
            request.method, url, headers=headers, content=request.stream()
        )
        r = await agent.context.llm_client.http_client.send(req, stream=True)
        
        async def stream_generator():
            try:
                async for chunk in r.aiter_bytes():
                    yield chunk
            finally:
                await r.aclose()
                
        return StreamingResponse(stream_generator(), status_code=r.status_code, media_type=r.headers.get("content-type"))
    except Exception as e:
        return JSONResponse({"error": f"Proxy Error: {e}"}, 502)